packages:
  - "apps/*"
  - "packages/*"

confirmModulesPurge: false

allowBuilds:
  browser-tabs-lock: false
  bufferutil: false
  core-js: true
  unrs-resolver: true
  utf-8-validate: false

minimumReleaseAgeExclude:
  - expo-file-system@57.0.4
  - expo-image-picker@57.0.10
