export const internalReadinessNotice = {
  title: "Internal readiness only",
  detail:
    "This page is an operator checklist for FieldDoc setup. It is not a customer Proof Packet and should not be exported or sent outside your team.",
  printTitle: "Internal readiness page - not a Proof Packet",
  printDetail:
    "Return to Reports and use the customer Proof Packet download for customer delivery.",
} as const;

export const proofPacketDownloadLabel = "Download customer Proof Packet PDF";

export const proofPacketArchiveGuidance =
  "Customer-ready Proof Packets are generated by the report workflow and downloaded from archived report PDFs, not by printing Settings.";
