export const internalReadinessNotice = {
  title: "Internal readiness only",
  detail:
    "This page is an operator checklist for FieldDoc setup. It is not a customer report and should not be exported or sent outside your team.",
  printTitle: "Internal readiness page - not a customer report",
  printDetail:
    "Return to Reports and use the customer FieldDoc report download for delivery.",
} as const;

export const proofPacketDownloadLabel = "Download customer FieldDoc Report";

export const proofPacketArchiveGuidance =
  "Customer-ready FieldDoc reports are generated by the report workflow and downloaded from the report archive, not by printing Settings.";
